from enum import Enum


class TaskErrorCode(str, Enum):
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_TITLE_REQUIRED = "TASK_TITLE_REQUIRED"
    TASK_TITLE_TOO_LONG = "TASK_TITLE_TOO_LONG"
    TASK_TITLE_INVALID = "TASK_TITLE_INVALID"
    TASK_DUE_AT_INVALID = "TASK_DUE_AT_INVALID"
    TASK_DUE_AT_TIMEZONE_REQUIRED = "TASK_DUE_AT_TIMEZONE_REQUIRED"
    TASK_DUE_AT_IN_PAST = "TASK_DUE_AT_IN_PAST"
    TASK_DUE_RANGE_REQUIRED = "TASK_DUE_RANGE_REQUIRED"
    TASK_DUE_RANGE_TIMEZONE_REQUIRED = "TASK_DUE_RANGE_TIMEZONE_REQUIRED"
    TASK_DUE_RANGE_ORDER_INVALID = "TASK_DUE_RANGE_ORDER_INVALID"
    TASK_DUE_RANGE_INVALID = "TASK_DUE_RANGE_INVALID"
    TASK_ID_INVALID = "TASK_ID_INVALID"
    TASK_PAGE_INVALID = "TASK_PAGE_INVALID"
    TASK_PAGE_SIZE_INVALID = "TASK_PAGE_SIZE_INVALID"
    TASK_SEARCH_TOO_LONG = "TASK_SEARCH_TOO_LONG"
    TASK_STATUS_FILTER_INVALID = "TASK_STATUS_FILTER_INVALID"
    TASK_SORT_FIELD_INVALID = "TASK_SORT_FIELD_INVALID"
    TASK_SORT_DIRECTION_INVALID = "TASK_SORT_DIRECTION_INVALID"
    TASK_COMPLETION_STATUS_INVALID = "TASK_COMPLETION_STATUS_INVALID"


class TaskValidationError(ValueError):
    def __init__(self, code: TaskErrorCode) -> None:
        self.code = code
        super().__init__(code.value)
